const USER_REGISTERED = "USER_REGISTERED";
const GET_ERRORS = "GET_ERRORS";
const USER_LOGGED_IN = "USER_LOGGED_IN";
const USER_LOGGED_OUT = "USER_LOGGED_OUT";
const CLEAR_ERROR = "CLEAR_ERROR";
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";

export {
  USER_REGISTERED, GET_ERRORS, USER_LOGGED_IN, CLEAR_ERROR, USER_LOGGED_OUT, CLEAR_CURRENT_USER
};
