const USER_REGISTERED = "USER_REGISTERED";
const GET_ERRORS = "GET_ERRORS";
const USER_LOGGED_IN = "USER_LOGGED_IN";
const USER_LOGGED_OUT = "USER_LOGGED_OUT";
const CLEAR_ERROR = "CLEAR_ERROR";
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";
const GET_ALL_MENU = "GET_ALL_MENU";
const MENU_LOADING = "MENU_LOADING";
const GET_SINGLE_MENU = "GET_SINGLE_MENU";
const MAKE_ORDER = "MAKE_ORDER";
const GET_ORDERS = "GET_ORDERS";
const ORDER_LOADING = "ORDER_LOADING";
const ADMIN_GET_ORDERS = "ADMIN_GET_ORDERS";
const ADD_MENU = "ADD_MENU";
const ACCEPT_ORDER = "ACCEPT_ORDER";
const GET_SINGLE_ORDER = "GET_SINGLE_ORDER";
const DECLINE_ORDER = "DECLINE_ORDER";
const COMPLETE_ORDER = "COMPLETE_ORDER";

export {
  USER_REGISTERED, GET_ERRORS, USER_LOGGED_IN, CLEAR_ERROR, USER_LOGGED_OUT,
  CLEAR_CURRENT_USER, GET_ALL_MENU, MENU_LOADING, GET_SINGLE_MENU, MAKE_ORDER,
  GET_ORDERS, ORDER_LOADING, ADMIN_GET_ORDERS, ADD_MENU, ACCEPT_ORDER,
  GET_SINGLE_ORDER, DECLINE_ORDER, COMPLETE_ORDER
};
